language: go

go:
- 1.11.x
- master

os:
- linux
- osx
- windows

dist: trusty
sudo: false

install:
- go get github.com/golang/glog

before_script:
- env GO111MODULE=on go build
- env GO111MODULE=on go test

script:
- go test -v ./snowflake/snowflake
- go run ./main.go
